# Generated by Django 2.2.4 on 2019-08-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='reted_user',
            new_name='rated_user',
        ),
    ]
